import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import AppHeader from "@/components/AppHeader/AppHeader";
import Sider from "antd/es/layout/Sider";
import { Content } from "antd/es/layout/layout";
import AppSideMenu from "@/components/AppSideMenu/AppSideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
            crossOrigin="anonymous"
          /> */}
      </head>
      <body className={inter.className}>
        <AntdRegistry>
          <Layout>
            <AppHeader />
            <Layout hasSider>
              <Sider
                theme="light"
                style={{
                  left: 0,
                  borderRight: "1px solid #f1f1f1",
                  height: "calc(100vh - 64px)",
                }}
              >
                <AppSideMenu />
              </Sider>
              <Layout>
                <Content
                  style={{ padding: "25px", minHeight: "calc(100vh - 64px)" }}
                >
                  {" "}
                  {children}
                </Content>
              </Layout>
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
